# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20171003_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(default='F-stop| Shutter Speed | ISO', max_length=400),
        ),
    ]
