# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20171003_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sub_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
