# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
